version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=orders
    volumes:
      - mysql:/var/lib/mysql

  postgres:
    image: postgres:14.8
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=revenue
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql14/data
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mysql:
  pgdata:
  local-file-storage:
  localstack: